name: 'Shared PHP'
description: 'Setup job for the workflows'
inputs:
  php-version:
    description: 'PHP version'
    required: true
    default: '8.2'
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pdo_mysql
        coverage: pcov
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      shell: bash
      run: composer validate

    - name: Get Composer Cache Directory
      shell: bash
      id: composer-cache
      run: echo "composer_cache_dir=$(composer config cache-files-dir)" >> $GITHUB_ENV 

    - name: Cache Composer packages
      uses: actions/cache@v2
      with:
        path: ${{ env.composer_cache_dir }}
        key: ${{ runner.OS }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.OS }}-composer-
        
    - name: Install Composer dependencies
      shell: bash
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Install Symfony CLI
      shell: bash
      run: |
        curl -sS https://get.symfony.com/cli/installer | bash
        mkdir -p $HOME/bin
        mv /home/runner/.symfony5/bin/symfony $HOME/bin/
